# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1057, 615)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 70, 251, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.playBtn.setObjectName("playBtn")
        self.horizontalLayout.addWidget(self.playBtn)
        self.stopBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout.addWidget(self.stopBtn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 100, 251, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 130, 251, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 160, 251, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.XCoordEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.XCoordEdit.setMaxLength(800)
        self.XCoordEdit.setObjectName("XCoordEdit")
        self.horizontalLayout_4.addWidget(self.XCoordEdit)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 190, 251, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.YCoordEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.YCoordEdit.setMaxLength(800)
        self.YCoordEdit.setObjectName("YCoordEdit")
        self.horizontalLayout_5.addWidget(self.YCoordEdit)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 40, 251, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.filenameLbl = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.filenameLbl.setObjectName("filenameLbl")
        self.horizontalLayout_7.addWidget(self.filenameLbl)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 10, 251, 32))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.browseBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.browseBtn.setObjectName("browseBtn")
        self.horizontalLayout_6.addWidget(self.browseBtn)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(0, 220, 251, 31))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.carsLbl1 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.carsLbl1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.carsLbl1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.carsLbl1.setLineWidth(3)
        self.carsLbl1.setMidLineWidth(0)
        self.carsLbl1.setScaledContents(True)
        self.carsLbl1.setWordWrap(False)
        self.carsLbl1.setObjectName("carsLbl1")
        self.horizontalLayout_8.addWidget(self.carsLbl1)
        self.carsLbl = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.carsLbl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.carsLbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.carsLbl.setLineWidth(3)
        self.carsLbl.setMidLineWidth(0)
        self.carsLbl.setScaledContents(True)
        self.carsLbl.setWordWrap(False)
        self.carsLbl.setObjectName("carsLbl")
        self.horizontalLayout_8.addWidget(self.carsLbl)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(250, 10, 791, 591))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.image_label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.horizontalLayout_10.addWidget(self.image_label)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(0, 250, 251, 31))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_11.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.sEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.sEdit.setInputMask("")
        self.sEdit.setMaxLength(800)
        self.sEdit.setObjectName("sEdit")
        self.horizontalLayout_11.addWidget(self.sEdit)
        self.listWidget = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 290, 231, 301))
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Детектор авто"))
        self.playBtn.setText(_translate("MainWindow", "Play"))
        self.stopBtn.setText(_translate("MainWindow", "Stop"))
        self.label_4.setText(_translate("MainWindow", "Положение по X:"))
        self.XCoordEdit.setText(_translate("MainWindow", "425"))
        self.label_5.setText(_translate("MainWindow", "Положение по Y:"))
        self.YCoordEdit.setText(_translate("MainWindow", "300"))
        self.filenameLbl.setText(_translate("MainWindow", "Видео:"))
        self.label.setText(_translate("MainWindow", "Выберите видео:"))
        self.browseBtn.setText(_translate("MainWindow", "..."))
        self.carsLbl1.setText(_translate("MainWindow", "Кол-во авто: "))
        self.carsLbl.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Пороговая интенсивность:"))
        self.sEdit.setText(_translate("MainWindow", "30"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

